---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dynamicw/YourApp/
    - /bin/bash -c "composer install --no-dev --optimize-autoloader"
    - /bin/rsync -av --exclude=".git" --exclude=".cpanel.yml" --exclude="storage/logs/*" --exclude="storage/framework/sessions/*" --exclude="storage/framework/views/*" --exclude="bootstrap/cache/*" . $DEPLOYPATH
